import "dotenv/config"

export const CONFIG = {
  network: (process.env.TON_NETWORK || "mainnet") as "mainnet" | "testnet",
  rpcEndpoint: process.env.TON_RPC_ENDPOINT || process.env.TONCENTER_API_KEY ? "https://toncenter.com/api/v2/jsonRPC" : "",
  tonApiKey: process.env.TONAPI_KEY || "",
  tonapiBase: process.env.TONAPI_BASE || "https://tonapi.io/v2",
  mnemonic: process.env.WALLET_MASTER_MNEMONIC || process.env.WALLET_MNEMONIC || "",
  walletVersion: (process.env.WALLET_VERSION || "v5r1") as "v3r2" | "v4r2" | "v5r1",
  walletSubwalletId: Number(process.env.WALLET_SUBWALLET_ID || 698983191),
  publicWebhookUrl: process.env.PUBLIC_WEBHOOK_URL || "",
  observeOnly: String(process.env.OBSERVE_ONLY || "false").toLowerCase() === "true",
  agentSharedSecret: process.env.AGENT_SHARED_SECRET || "",
  nvidiaApiKey: process.env.NVIDIA_API_KEY || process.env.NIM_API_KEY || "",
  nvidiaModel: process.env.NVIDIA_MODEL || "openai/gpt-oss-120b",
  exaApiKey: process.env.EXA_API_KEY || "",
  strategy: {
    maxRiskPct: Number(process.env.MAX_PORTFOLIO_RISK_PCT || 15),
    minBankrollTon: Number(process.env.MIN_WALLET_BANKROLL_TON || 0),
    buyAmountTon: Number(process.env.BUY_AMOUNT_TON || 0) || Number(process.env.DEFAULT_SNIPE_TON || 0.5),
    defaultSnipeTon: Number(process.env.DEFAULT_SNIPE_TON || 0.5),
    slippageTolerance: Number(process.env.SLIPPAGE_TOLERANCE || 15),
    stopLossPct: Number(process.env.STOP_LOSS_PCT || 35),
    takeProfitT1Pct: Number(process.env.TAKE_PROFIT_T1_PCT || 100),
    preferredDex: (process.env.PREFERRED_DEX || "stonfi") as "stonfi" | "dedust",
    poolMinimumTon: Number(process.env.POOL_MINIMUM_TON || 0.05),
    auditCacheTtlMs: Number(process.env.AUDIT_CACHE_TTL_MS || 300_000),
    deadPoolCacheTtlMs: Number(process.env.DEAD_POOL_CACHE_TTL_MS || 300_000),
    auditRequireRenounce: String(process.env.AUDIT_REQUIRE_RENOUNCE || "true").toLowerCase() !== "false",
    monitorIntervalMs: Number(process.env.MONITOR_INTERVAL_MS || 10_000),
    radarIntervalMs: Number(process.env.RADAR_INTERVAL_MS || 300_000),
    trendExitEnabled: String(process.env.TREND_EXIT_ENABLED || "true").toLowerCase() === "true",
    trendExitFastEma: Number(process.env.TREND_EXIT_FAST_EMA || 7),
    trendExitSlowEma: Number(process.env.TREND_EXIT_SLOW_EMA || 25),
    trendExitConfirmTicks: Number(process.env.TREND_EXIT_CONFIRM_TICKS || 3),
    trendExitHistory: Number(process.env.TREND_EXIT_HISTORY || 60),
    trendExitMinObservations: Number(process.env.TREND_EXIT_MIN_OBSERVATIONS || 6),
    trendExitConfirmEnabled: String(process.env.TREND_EXIT_CONFIRM_ENABLED || "true").toLowerCase() === "true",
    volatilityRegimeEnabled: String(process.env.VOLATILITY_REGIME_ENABLED || "true").toLowerCase() === "true",
    volatilityLookback: Number(process.env.VOLATILITY_LOOKBACK || 14),
    volatilitySpikeThreshold: Number(process.env.VOLATILITY_SPIKE_THRESHOLD || 2.5),
    volatilityCalmRatio: Number(process.env.VOLATILITY_CALM_RATIO || 0.5),
    volatilityConfirmTicks: Number(process.env.VOLATILITY_CONFIRM_TICKS || 2),
    stopAtrMult: Number(process.env.STOP_ATR_MULT || 1.0),
    stopConfirmTicks: Number(process.env.STOP_CONFIRM_TICKS || 2),
    trendExitAtrMult: Number(process.env.TREND_EXIT_ATR_MULT || 3.0),
    trendExitSpikedExtraTicks: Number(process.env.TREND_EXIT_SPIKED_EXTRA_TICKS || 2),
  },
  watchlist: (process.env.WATCHLIST || "").split(",").map((s) => s.trim()).filter(Boolean),
  orchestration: {
    strategyDepthCapPct: Number(process.env.STRATEGY_DEPTH_CAP_PCT || 5),
    strategyCautionSizePct: Number(process.env.STRATEGY_CAUTION_SIZE_PCT || 50),
    strategyMinSizeTon: Number(process.env.STRATEGY_MIN_SIZE_TON || 0.05),
    scannerMinPoolTvlTon: Number(process.env.SCANNER_MIN_POOL_TVL_TON || 10),
    scannerMinPoolLiquidityTon: Number(process.env.SCANNER_MIN_POOL_LIQUIDITY_TON || 5),
    scannerScanLimit: Number(process.env.SCANNER_SCAN_LIMIT || 20),
    scannerTopN: Number(process.env.SCANNER_TOP_N || 5),
  },
}
